// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVYTp7R34j4W6B4hfdirbIIe4aTfxJHyQ',
    appId: '1:212216633840:web:9dfa7a69ea6d1c3fade535',
    messagingSenderId: '212216633840',
    projectId: 'fuel-tracker-5dd68',
    authDomain: 'fuel-tracker-5dd68.firebaseapp.com',
    storageBucket: 'fuel-tracker-5dd68.firebasestorage.app',
    measurementId: 'G-M2VWKD9WY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVLX4vcR-cM28-5zVwhSn4mX__kVmh8ZI',
    appId: '1:212216633840:android:3105919ce49b733bade535',
    messagingSenderId: '212216633840',
    projectId: 'fuel-tracker-5dd68',
    storageBucket: 'fuel-tracker-5dd68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13MqIAIFdAhnOLBnEMvlZoudEc1c9kK0',
    appId: '1:212216633840:ios:1a245da837eb1232ade535',
    messagingSenderId: '212216633840',
    projectId: 'fuel-tracker-5dd68',
    storageBucket: 'fuel-tracker-5dd68.firebasestorage.app',
    iosBundleId: 'com.example.fueltrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13MqIAIFdAhnOLBnEMvlZoudEc1c9kK0',
    appId: '1:212216633840:ios:1a245da837eb1232ade535',
    messagingSenderId: '212216633840',
    projectId: 'fuel-tracker-5dd68',
    storageBucket: 'fuel-tracker-5dd68.firebasestorage.app',
    iosBundleId: 'com.example.fueltrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVYTp7R34j4W6B4hfdirbIIe4aTfxJHyQ',
    appId: '1:212216633840:web:fc023ece96aa2eeeade535',
    messagingSenderId: '212216633840',
    projectId: 'fuel-tracker-5dd68',
    authDomain: 'fuel-tracker-5dd68.firebaseapp.com',
    storageBucket: 'fuel-tracker-5dd68.firebasestorage.app',
    measurementId: 'G-GW4E3YHYB6',
  );
}
